export {
  closeDatabase,
  createDatabase,
  type CreateDatabaseOptions,
  type Database,
} from "./database.js";

export {
  appendAnalyticsEvent,
  archiveCampaign,
  ConcurrentCampaignUpdateError,
  createCampaign,
  DevelopmentJobPayloadConflictError,
  ensureWorkspaceForUser,
  getCampaign,
  getCampaignDetailView,
  getWorkspaceForOwner,
  ingestDevelopmentJob,
  InvalidCampaignTransitionError,
  listCampaignMatchViews,
  listCampaigns,
  updateCampaign,
  type CampaignDetailView,
  type CampaignMatchView,
  type CampaignUpstreamWorkView,
  type CreateCampaignInput,
  type IngestDevelopmentJobInput,
  type IngestDevelopmentJobResult,
  type UpdateCampaignInput,
} from "./repositories.js";

export {
  commitJobMatches,
  commitJobNormalization,
  commitMatchAnalysis,
  loadJobForNormalization,
  loadJobMatchContext,
  loadMatchAnalysisContext,
  type CommitJobMatchesResult,
  type CommitJobNormalizationResult,
  type CommitMatchAnalysisResult,
  type LoadJobForNormalizationResult,
  type LoadJobMatchContextResult,
  type LoadMatchAnalysisContextResult,
  type MatchableCampaign,
  type PositiveJobMatchInput,
} from "./pipeline.js";

export {
  claimWorkflowTask,
  completeWorkflowTask,
  enqueueWorkflowTask,
  failWorkflowTask,
  recoverExpiredWorkflowTasks,
  retryDeadWorkflowTask,
  renewWorkflowTaskLease,
  type ClaimedWorkflowTask,
  type EnqueueWorkflowTaskInput,
  type EnqueueWorkflowTaskResult,
  type FailWorkflowTaskResult,
} from "./workflow.js";

export {
  commitUpworkMonitorPoll,
  enableConnectedUpworkMonitor,
  enableFakeUpworkMonitor,
  getCampaignMonitorView,
  loadUpworkMonitorPollContext,
  pauseUpworkMonitor,
  UpworkMonitorConfigurationError,
  type CampaignMonitorView,
  type CommitUpworkMonitorPollResult,
  type LoadUpworkMonitorPollContextResult,
} from "./upwork-monitor.js";

export {
  purgeExpiredUpworkData,
  type PurgeExpiredUpworkDataResult,
} from "./upwork-retention.js";

export {
  commitKnowledgeIndex,
  commitProposalGeneration,
  createKnowledgeDocument,
  failKnowledgeIndex,
  failProposalGeneration,
  loadKnowledgeIndexContext,
  loadProposalGenerationQuery,
  loadProposalGenerationContext,
  listKnowledgeDocuments,
  listProposalQueueViews,
  regenerateProposal,
  reviewProposal,
  type CommitProposalGenerationResult,
  type CreateKnowledgeDocumentResult,
  type LoadKnowledgeIndexContextResult,
  type KnowledgeDocumentView,
  type ProposalGenerationContextResult,
  type ProposalGenerationQueryResult,
  type ProposalQueueView,
} from "./proposals.js";

export {
  beginUpworkOAuthConnection,
  completeUpworkOAuthConnection,
  disconnectUpworkOAuthConnection,
  getUpworkOAuthConnectionView,
  requireUpworkOAuthReconnect,
  UpworkOAuthConnectionConfigurationError,
  type UpworkOAuthConnectionView,
} from "./upwork-oauth-connections.js";

export {
  createDatabaseUpworkOAuthAuthorizationVault,
  hashUpworkOAuthState,
  UpworkOAuthAuthorizationNotFoundError,
  UpworkOAuthAuthorizationStateError,
  type UpworkOAuthAuthorizationVault,
} from "./upwork-oauth-authorizations.js";

export {
  createDatabaseUpworkOAuthCredentialVault,
  UpworkOAuthCredentialCipher,
  UpworkOAuthCredentialConfigurationError,
  UpworkOAuthCredentialDecryptionError,
  upworkOAuthAuthorizationPayloadSchema,
  upworkOAuthClientInformationSchema,
  upworkOAuthCredentialPayloadSchema,
  upworkOAuthDiscoverySchema,
  type UpworkOAuthAuthorizationPayload,
  type UpworkOAuthClientInformation,
  type UpworkOAuthCredentialPayload,
  type UpworkOAuthCredentialVault,
} from "./upwork-oauth-credentials.js";

export {
  aiScores,
  analyticsEvents,
  campaigns,
  campaignJobMatches,
  knowledgeDocumentStatusEnum,
  knowledgeDocuments,
  knowledgeChunks,
  proposalStatusEnum,
  proposals,
  proposalVersions,
  campaignStatusEnum,
  experienceLevelEnum,
  hoursPerWeekBandEnum,
  jobs,
  jobStatusEnum,
  jobTypeEnum,
  matchPipelineStatusEnum,
  pricingDirectionEnum,
  projectLengthBandEnum,
  suitabilityRecommendationEnum,
  upworkConnectionStatusEnum,
  upworkConnections,
  upworkOAuthAuthorizations,
  upworkOAuthCredentials,
  upworkJobObservations,
  upworkMonitorStatusEnum,
  upworkMonitors,
  workflowTaskKindEnum,
  workflowTasks,
  workflowTaskStatusEnum,
  workspaces,
  type AiScoreRow,
  type AnalyticsEventRow,
  type CampaignJobMatchRow,
  type KnowledgeDocumentRow,
  type KnowledgeChunkRow,
  type ProposalRow,
  type ProposalVersionRow,
  type CampaignRow,
  type JobRow,
  type UpworkJobObservationRow,
  type JsonObject,
  type JsonPrimitive,
  type JsonValue,
  type WorkflowTaskRow,
  type UpworkConnectionRow,
  type UpworkOAuthAuthorizationRow,
  type UpworkOAuthCredentialRow,
  type UpworkMonitorRow,
  type WorkspaceRow,
} from "./schema.js";
